### ISSUE TITLE
Add the possiblity to hide the workspace name?

### ISSUE THREAD

**Issue by bilelmoussaoui** [dyson/indicator-workspaces#1]
Hello,
i would like to ask you to add the possiblity to hide the workspace name from the panel? when you have to many indicators its take to much space!!

Thank you :)

**Comment by dyson** [comment]
Hi bil-elmoussaoui,

Hiding the workspace name form the panel was added in 0.4. You can download the latest version (0.5) from http://dysonsimmons.com/indicator-workspaces/ and install it over the top of the version you are running. Log out and back in and then in the preferences window you will be able to toggle the labels show/hide.

This raises an interesting point though, people can't see what version they are using or if a new version is out with new features. I'll have to have a think about how best to solve that.

Let me know how you go installing the new version.

**Comment by bilelmoussaoui** [comment]
Hey @dyson :) 
I was installing the 0.3 version ( i guess its most famous one); and i just did upgrade the last version (0.5).
i believe you have to ask elementary to add your deb package to their official repository as its one of the most useful indicators (for me) 
Thank you !!
